all:
  hosts:
    srvveeam01:
      ansible_host: 172.20.33.26
      ansible_port: 5985  # Porta padrão do WinRM
      ansible_user: Administrator
      ansible_password: 200DEV200@
      ansible_connection: winrm
      ansible_winrm_transport: basic
      ansible_winrm_server_cert_validation: ignore
      ansible_winrm_scheme: http  # ou 'https' se WinRM estiver configurado para HTTPS
