---
- name: Playbook para criar inventário do Windows
  hosts: all
  gather_facts: no  # Desativa a coleta automática de fatos para este playbook

  tasks:
    - name: Obter informações do sistema usando systeminfo
      win_command: systeminfo
      register: system_info
      changed_when: false

    - name: Exibir saída do comando systeminfo
      debug:
        var: system_info.stdout

    - name: Criar inventário do Windows
      set_fact:
        windows_inventory:
          hostname: "{{ ansible_hostname }}"
          os_version: "{{ system_info.stdout_lines | select('match', '^OS Version.*$') | map('split', ':') | last | join(':') | trim }}"
          memory: "{{ system_info.stdout_lines | select('match', '^Total Physical Memory.*$') | map('split', ':') | last | join(':') | trim }}"
          processor: "{{ system_info.stdout_lines | select('match', '^Processor\(s\):.*$') | map('split', ':') | last | join(':') | trim }}"

    - name: Exibir inventário do Windows
      debug:
        var: windows_inventory

